import os
import sys

# Ensure the local directory is in path for sibling imports
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from compiler import Compiler

def main():
    """Main entry point for the ELIN compiler."""
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <source_file.elin>")
        sys.exit(1)

    source_path = sys.argv[1]
    if not os.path.exists(source_path):
        print(f"Error: File '{source_path}' not found.")
        sys.exit(1)

    stem = os.path.splitext(os.path.basename(source_path))[0]
    output_path = stem + ".outz"
    package_name = stem

    try:
        with open(source_path, "r") as f:
            lines = f.readlines()
        
        compiler = Compiler(package_name)
        bytecode_output = compiler.compile(lines)
        
        with open(output_path, "w") as f:
            f.write(bytecode_output)
            
        print(f"✓ Compilation successful: {source_path} -> {output_path}")
        print(f"\nGenerated Bytecode:")
        print(bytecode_output)

    except Exception as e:
        print(f"Error during compilation: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)

if __name__ == "__main__":
    main()