import sys
from pathlib import Path
from compiler import compile, format_bytecode

def main():
    """
    Main entry point for the ELIN compiler.
    Expects a source file path as the first argument.
    """
    
    # Check if a filename was provided
    if len(sys.argv) < 2:
        print(f"Usage: python {sys.argv[0]} <your_source_file.elin>")
        return

    source_file_path = Path(sys.argv[1])
    
    # Ensure the file actually exists
    if not source_file_path.exists():
        print(f"Compilation Error: Could not find '{source_file_path}'.")
        return

    # Use the filename (without .elin) for the output and package name
    program_base_name = source_file_path.stem
    output_file_name = f"{program_base_name}.outz"
    output_file_path = source_file_path.parent / output_file_name

    try:
        # 1. Read the input source file
        source_code_lines = source_file_path.read_text().splitlines()
        
        # 2. Compile it to bytecode
        state = compile(source_code_lines, program_base_name)
        compiled_bytecode = format_bytecode(state)
        
        # 3. Write the compiled bytecode to a file
        output_file_path.write_text(compiled_bytecode)
            
        print(f"Success! Compiled: {source_file_path.name} -> {output_file_name}")
        print("-" * 30)
        print("Generated Bytecode:")
        print(compiled_bytecode)
        print("-" * 30)

    except Exception as error_details:
        print(f"Unexpected Error during compilation: {error_details}")
        # Only show the full technical details if something really weird happens
        # import traceback; traceback.print_exc()

if __name__ == "__main__":
    main()